language: node_js
node_js: "6"

script:
  - echo "Hello Newt!"
  - npm run build

before_deploy:
  - npm install -g firebase-tools

deploy:
  provider: script
  script: firebase deploy --token "${FIREBASE_TOKEN}"
  on:
    branch: master

notifications:
  email: false
