language: node_js
node_js: "6"
cache: yarn
addons:
  code_climate:
    repo_token: ${CODE_CLIMATE_TOKEN}

script:
  - yarn unit
  - yarn build

after_success:
  - yarn global add codecov
  - codecov
  - test $TRAVIS_BRANCH = "master" &&
    npm i -g codeclimate-test-reporter &&
    codeclimate-test-reporter < ./test/unit/coverage/lcov.info

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  on:
    branch: master

notifications:
  email: false
