language: node_js
node_js: "6"
cache: yarn

script:
  - yarn test
  - yarn build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  on:
    branch: master

notifications:
  email: false
