language: node_js
node_js: "6"
cache: yarn
addons:
  code_climate:
    repo_token: ${CODE_CLIMATE_TOKEN}

script:
  - yarn unit
  - yarn build

after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then npm i -g codeclimate-test-reporter; fi
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then codeclimate-test-reporter < ./test/unit/coverage/lcov.info; fi

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  on:
    branch: master

notifications:
  email: false
