language: node_js
node_js: "6"
cache: yarn

script:
  - yarn test
  - yarn build

before_deploy:
  - npm i -g firebase-tools

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token "${FIREBASE_TOKEN}"
  on:
    branch: master

notifications:
  email: false
