language: node_js
node_js: "6"

install:
  - npm install -g firebase-tools

script:
  - echo "Hello Newt!"

after_success:
  - firebase deploy --token "${FIREBASE_TOKEN}"

notifications:
  email: false
