language: node_js
node_js: "6"

install:
  - npm install -g firebase-tools

script:
  - echo "Hello Newt!"

deploy:
  provider: script
  script: firebase deploy --token "${FIREBASE_TOKEN}"
  on:
    branch: master

notifications:
  email: false
