language: node_js
node_js: "6"
cache: yarn

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - yarn test
  - yarn build

after_script: greenkeeper-lockfile-upload

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  on:
    branch: master

notifications:
  email: false
