export const ROUTE_LOADING = 'ROUTE_LOADING'
export const ASYNC_LOADING = 'ASYNC_LOADING'

export const NOTE_FORM = 'NOTE_FORM'
export const NOTE_FORM_TEXT = 'NOTE_FORM_TEXT'
export const NOTE_FORM_COLOR = 'NOTE_FORM_COLOR'

export const NOTE_EDITOR = 'NOTE_EDITOR'
export const NOTE_EDITOR_SHOW = 'NOTE_EDITOR_SHOW'
export const NOTE_EDITOR_NOTE = 'NOTE_EDITOR_NOTE'
export const NOTE_EDITOR_TEXT = 'NOTE_EDITOR_TEXT'
export const NOTE_EDITOR_COLOR = 'NOTE_EDITOR_COLOR'
