export const EDIT_NOTE = 'EDIT_NOTE'
export const EDIT_NOTE_COLOR = 'EDIT_NOTE_COLOR'
export const EDIT_NOTE_MARKDOWN = 'EDIT_NOTE_MARKDOWN'
export const CLEAR_NOTE_FORM = 'CLEAR_NOTE_FORM'

export const NOTEFORM_TITLE = 'NOTEFORM_TITLE'
export const NOTEFORM_TEXT = 'NOTEFORM_TEXT'
export const NOTEFORM_COLOR = 'NOTEFORM_COLOR'
export const NOTEFORM_MARKDOWN = 'NOTEFORM_MARKDOWN'
